import React, { createContext, useState } from 'react';

// Create the ContactContext
export const ContactContext = createContext();

// ContactProvider component that will wrap your app and provide contact data to any component that needs it
export const ContactProvider = ({ children }) => {
    const [contacts, setContacts] = useState([
            {
              id: 1,
              name: 'Michael Scott',
              email: 'michael.scott@example.com',
              phone: '987-654-3210',
              address: '1725 Slough Avenue',
              role: 'prospect',
              interestAddress: '1725 Slough Avenue',
              budget: '300000',
              bedrooms: 2,
              bathrooms: 1,
              location: 'Scranton',
              wantsNeeds: 'Close to office',
              sellerA: 'janeA@example.com',
              timeFrame: '1 month',
              propertyType: ['Residential'],
              financingStatus: 'Pre-approved',
              additionalNotes: 'N/A',
              contactType: 'prospect',
              tasks: [
                { taskType: 'call', taskDescription: 'Follow up call', dueDate: '2024-08-01' },
                { taskType: 'email', taskDescription: 'Send property listings', dueDate: '2024-08-03' },
              ],
            },
            {
              id: 2,
              name: 'Pam Beesly',
              email: 'pam.beesly@example.com',
              phone: '876-543-2109',
              address: '435 Paper Street',
              role: 'prospect',
              interestAddress: '435 Paper Street',
              budget: '200000',
              bedrooms: 3,
              bathrooms: 2,
              location: 'Scranton',
              wantsNeeds: 'Near park',
              timeFrame: '2 months',
              propertyType: ['Residential'],
              financingStatus: 'Not approved',
              additionalNotes: 'Looking for a house with a big backyard.',
              contactType: 'prospect',
              tasks: [
                { taskType: 'call', taskDescription: 'Schedule home tour', dueDate: '2024-07-25' },
                { taskType: 'email', taskDescription: 'Discuss financing options', dueDate: '2024-07-30' },
              ],
            },
            {
              id: 3,
              name: 'Jim Halpert',
              email: 'jim.halpert@example.com',
              phone: '765-432-1098',
              address: '212 Sales Drive',
              role: 'prospect',
              interestAddress: '212 Sales Drive',
              budget: '250000',
              bedrooms: 4,
              bathrooms: 3,
              location: 'Scranton',
              wantsNeeds: 'Good neighborhood',
              timeFrame: '3 months',
              propertyType: ['Residential'],
              financingStatus: 'Cash buyer',
              additionalNotes: 'Prefers a quiet neighborhood.',
              contactType: 'prospect',
              tasks: [
                { taskType: 'call', taskDescription: 'Review neighborhood schools', dueDate: '2024-08-05' },
                { taskType: 'email', taskDescription: 'Meet with realtor', dueDate: '2024-08-10' },
              ],
            },
            {
              id: 4,
              name: 'Dwight Schrute',
              email: 'dwight.schrute@example.com',
              phone: '654-321-0987',
              address: '417 Beet Road',
              role: 'prospect',
              interestAddress: '417 Beet Road',
              budget: '400000',
              bedrooms: 5,
              bathrooms: 4,
              location: 'Scranton',
              wantsNeeds: 'Farmland',
              timeFrame: '6 months',
              propertyType: ['Residential', 'Land'],
              financingStatus: 'Pre-approved',
              additionalNotes: 'Needs land for beet farming.',
              contactType: 'prospect',
              tasks: [
                { taskType: 'call', taskDescription: 'Evaluate farmland quality', dueDate: '2024-07-28' },
                { taskType: 'email', taskDescription: 'Check zoning laws', dueDate: '2024-08-02' },
              ],
            },
            // Contacts
            {
              id: 5,
              name: 'John Doe',
              email: 'john@example.com',
              phone: '123-456-7890',
              mailAddress: '123 Main St',
              role: 'buyer',
              interestAddress: '123 Main St',
              budget: '500000',
              bedrooms: 3,
              bathrooms: 2,
              location: 'New York',
              wantsNeeds: 'Near park',
              subCat: 'searching',
              offer: '10,000',
              contactType: 'contact',
              tasks: [
                { taskType: 'call', taskDescription: 'Follow up on budget', dueDate: '2024-08-01' },
                { taskType: 'email', taskDescription: 'Send new property listings', dueDate: '2024-08-02' },
              ],
            },
            {
              id: 6,
              name: 'Jane Smith',
              email: 'jane@example.com',
              phone: '234-567-8901',
              mailAddress: '456 Elm St',
              role: 'seller',
              interestAddress: '456 Elm St',
              budget: '450000',
              commission: 6,
              sellerA: 'janeA@example.com',
              sellerB: 'janeB@example.com',
              financingStatus: 'Pre-approved',
              contactType: 'contact',
              tasks: [
                { taskType: 'text', taskDescription: 'Confirm showing schedule', dueDate: '2024-07-25' },
                { taskType: 'call', taskDescription: 'Discuss commission details', dueDate: '2024-07-30' },
              ],
            },
            {
              id: 7,
              name: 'Bob Johnson',
              email: 'bob@example.com',
              phone: '345-678-9012',
              mailAddress: '789 Oak St',
              role: 'investor',
              propertyType: 'Commercial',
              futureUse: 'Rental',
              budget: '1000000',
              location: 'Los Angeles',
              wantsNeeds: 'High ROI',
              contactType: 'contact',
              tasks: [
                { taskType: 'email', taskDescription: 'Send investment opportunities', dueDate: '2024-08-05' },
                { taskType: 'call', taskDescription: 'Discuss rental market trends', dueDate: '2024-08-10' },
              ],
            },
            {
              id: 8,
              name: 'Alice Brown',
              email: 'alice@example.com',
              phone: '456-789-0123',
              mailAddress: '101 Pine St',
              role: 'lead',
              interestAddress: '101 Pine St',
              budget: '600000',
              bedrooms: 4,
              bathrooms: 3,
              location: 'San Francisco',
              wantsNeeds: 'Good school district',
              timeFrame: '3 months',
              propertyType: ['Residential', 'Land'],
              contactType: 'contact',
              tasks: [
                { taskType: 'text', taskDescription: 'Check property availability', dueDate: '2024-07-28' },
                { taskType: 'call', taskDescription: 'Schedule meeting with realtor', dueDate: '2024-08-02' },
              ],
            },
            {
              id: 9,
              name: 'Charlie Davis',
              email: 'charlie@example.com',
              phone: '567-890-1234',
              address: '202 Maple St',
              role: 'buyer',
              interestAddress: '202 Maple St',
              budget: '700000',
              bedrooms: 5,
              bathrooms: 4,
              location: 'Chicago',
              wantsNeeds: 'Close to work',
              subCat: 'offer',
              mailAddress: '202 Maple St',
              offer: '650000',
              dueDiligence: '2 weeks',
              daysForClosing: '30 days',
              titleCompany: 'Best Title Co.',
              escrowAmount: '10000',
              paymentType: 'Cash',
              contactType: 'contact',
              tasks: [
                { taskType: 'email', taskDescription: 'Send offer details', dueDate: '2024-07-22' },
                { taskType: 'call', taskDescription: 'Discuss escrow amount', dueDate: '2024-07-23' },
              ],
            },
          

    ]);  // Initialize contacts with an empty array or with data

    return (
        <ContactContext.Provider value={{ contacts, setContacts }}>
            {children}
        </ContactContext.Provider>
    );
};
