import React, { createContext, useState } from 'react';

// Create the ContactContext
export const ContactContext = createContext();

// ContactProvider component that will wrap your app and provide contact data to any component that needs it
export const ContactProvider = ({ children }) => {
  const [contacts, setContacts] = useState([
    {
      id: 1,
      name: 'Michael Scott',
      email: 'michael.scott@example.com',
      phone: '987-654-3210',
      address: '1725 Slough Avenue',
      role: 'prospect',
      interestAddress: '1725 Slough Avenue',
      budget: '300000',
      bedrooms: 2,
      bathrooms: 1,
      location: 'Scranton',
      wantsNeeds: 'Close to office',
      sellerA: 'janeA@example.com',
      timeFrame: '1 month',
      propertyType: ['Residential'],
      financingStatus: 'Pre-approved',
      additionalNotes: 'N/A',
      contactType: 'prospect',
      tasks: [
        { taskId: 1, status: 'open', taskType: 'call', taskDescription: 'Follow up with client on offer', dueDate: '2024-09-05', urgency: 'high' },
        { taskId: 2, status: 'open', taskType: 'email', taskDescription: 'Send property details to buyer', dueDate: '2024-09-06', urgency: 'medium' },
        { taskId: 3, status: 'open', taskType: 'appointment', taskDescription: 'Schedule property viewing', dueDate: '2024-09-07', urgency: 'low' },
      ],
    },
    {
      id: 2,
      name: 'Pam Beesly',
      email: 'pam.beesly@example.com',
      phone: '876-543-2109',
      address: '435 Paper Street',
      role: 'prospect',
      interestAddress: '435 Paper Street',
      budget: '200000',
      bedrooms: 3,
      bathrooms: 2,
      location: 'Scranton',
      wantsNeeds: 'Near park',
      timeFrame: '2 months',
      propertyType: ['Residential'],
      financingStatus: 'Not approved',
      additionalNotes: 'Looking for a house with a big backyard.',
      contactType: 'prospect',
      tasks: [
        { taskId: 4, status: 'open', taskType: 'text', taskDescription: 'Confirm appointment time with client', dueDate: '2024-09-08', urgency: 'medium' },
        { taskId: 5, status: 'open', taskType: 'call', taskDescription: 'Discuss financing options with lender', dueDate: '2024-09-09', urgency: 'high' },
        { taskId: 6, status: 'open', taskType: 'email', taskDescription: 'Send final contract to seller', dueDate: '2024-09-10', urgency: 'low' },
      ],
    },
    {
      id: 3,
      name: 'Jim Halpert',
      email: 'jim.halpert@example.com',
      phone: '765-432-1098',
      address: '212 Sales Drive',
      role: 'prospect',
      interestAddress: '212 Sales Drive',
      budget: '250000',
      bedrooms: 4,
      bathrooms: 3,
      location: 'Scranton',
      wantsNeeds: 'Good neighborhood',
      timeFrame: '3 months',
      propertyType: ['Residential'],
      financingStatus: 'Cash buyer',
      additionalNotes: 'Prefers a quiet neighborhood.',
      contactType: 'prospect',
      tasks: [
        { taskId: 7, status: 'open', taskType: 'appointment', taskDescription: 'Meeting with title company', dueDate: '2024-09-11', urgency: 'medium' },
      ],
    },
    {
      id: 4,
      name: 'Dwight Schrute',
      email: 'dwight.schrute@example.com',
      phone: '654-321-0987',
      address: '417 Beet Road',
      role: 'prospect',
      interestAddress: '417 Beet Road',
      budget: '400000',
      bedrooms: 5,
      bathrooms: 4,
      location: 'Scranton',
      wantsNeeds: 'Farmland',
      timeFrame: '6 months',
      propertyType: ['Residential', 'Land'],
      financingStatus: 'Pre-approved',
      additionalNotes: 'Needs land for beet farming.',
      contactType: 'prospect',
      tasks: [
        { taskId: 8, status: 'open', taskType: 'call', taskDescription: 'Update buyer on escrow progress', dueDate: '2024-09-12', urgency: 'high' },
        { taskId: 9, status: 'open', taskType: 'text', taskDescription: 'Reminder to submit inspection report', dueDate: '2024-09-13', urgency: 'low' },
      ],
    },
    // Contacts
    {
      id: 5,
      name: 'John Doe',
      email: 'john@example.com',
      phone: '123-456-7890',
      mailAddress: '123 Main St',
      role: 'buyer',
      interestAddress: '123 Main St',
      budget: '500000',
      bedrooms: 3,
      bathrooms: 2,
      location: 'New York',
      wantsNeeds: 'Near park',
      subCat: 'searching',
      offer: '10,000',
      contactType: 'contact',
      tasks: [
        { taskId: 10, status: 'open', taskType: 'email', taskDescription: 'Request documents from seller', dueDate: '2024-09-14', urgency: 'medium' },
        { taskId: 11, status: 'open', taskType: 'appointment', taskDescription: 'Walkthrough of new listing', dueDate: '2024-09-15', urgency: 'low' },
      ],
    },
    {
      id: 6,
      name: 'Jane Smith',
      email: 'jane@example.com',
      phone: '234-567-8901',
      mailAddress: '456 Elm St',
      role: 'seller',
      interestAddress: '456 Elm St',
      budget: '450000',
      commission: 6,
      sellerA: 'janeA@example.com',
      sellerB: 'janeB@example.com',
      financingStatus: 'Pre-approved',
      contactType: 'contact',
      tasks: [
        { taskId: 12, status: 'open', taskType: 'call', taskDescription: 'Discuss final offer with buyer', dueDate: '2024-09-16', urgency: 'high' },
        { taskId: 13, status: 'open', taskType: 'email', taskDescription: 'Send updated listing to all clients', dueDate: '2024-09-17', urgency: 'medium' },
      ],
    },
    {
      id: 7,
      name: 'Bob Johnson',
      email: 'bob@example.com',
      phone: '345-678-9012',
      mailAddress: '789 Oak St',
      role: 'investor',
      propertyType: 'Commercial',
      futureUse: 'Rental',
      budget: '1000000',
      location: 'Los Angeles',
      wantsNeeds: 'High ROI',
      contactType: 'contact',
      tasks: [
        { taskId: 14, status: 'open', taskType: 'appointment', taskDescription: 'Open house event planning', dueDate: '2024-09-18', urgency: 'low' },
      ],
    },
    {
      id: 8,
      name: 'Alice Brown',
      email: 'alice@example.com',
      phone: '456-789-0123',
      mailAddress: '101 Pine St',
      role: 'lead',
      interestAddress: '101 Pine St',
      budget: '600000',
      bedrooms: 4,
      bathrooms: 3,
      location: 'San Francisco',
      wantsNeeds: 'Good school district',
      timeFrame: '3 months',
      propertyType: ['Residential', 'Land'],
      contactType: 'contact',
      tasks: [
        { taskId: 15, status: 'open', taskType: 'text', taskDescription: 'Confirm contract signature from buyer', dueDate: '2024-09-19', urgency: 'high' },
        { taskId: 16, status: 'open', taskType: 'call', taskDescription: 'Review inspection report with seller', dueDate: '2024-09-20', urgency: 'medium' },
      ],
    },
    {
      id: 9,
      name: 'Charlie Davis',
      email: 'charlie@example.com',
      phone: '567-890-1234',
      address: '202 Maple St',
      role: 'buyer',
      interestAddress: '202 Maple St',
      budget: '700000',
      bedrooms: 5,
      bathrooms: 4,
      location: 'Chicago',
      wantsNeeds: 'Close to work',
      subCat: 'offer',
      mailAddress: '202 Maple St',
      offer: '650000',
      dueDiligence: '2 weeks',
      daysForClosing: '30 days',
      titleCompany: 'Best Title Co.',
      escrowAmount: '10000',
      paymentType: 'Cash',
      contactType: 'contact',
      tasks: [
        { taskId: 17, status: 'open', taskType: 'email', taskDescription: 'Send list of repairs to buyer', dueDate: '2024-09-21', urgency: 'low' },
        { taskId: 18, status: 'open', taskType: 'appointment', taskDescription: 'Closing meeting with buyer', dueDate: '2024-09-22', urgency: 'high' },
        { taskId: 19, status: 'open', taskType: 'text', taskDescription: 'Remind seller to prepare documents for closing', dueDate: '2024-09-23', urgency: 'medium' },
        { taskId: 20, status: 'open', taskType: 'email', taskDescription: 'Follow up on payment for closing', dueDate: '2024-09-24', urgency: 'low' }
      ],
    },


  ]);  // Initialize contacts with an empty array or with data

  return (
    <ContactContext.Provider value={{ contacts, setContacts }}>
      {children}
    </ContactContext.Provider>
  );
};
