import React, { createContext, useState } from 'react';

export const PropertyContext = createContext();

export const PropertyProvider = ({ children }) => {
    const [properties, setProperties] = useState([
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '456 Maple Avenue',
            city: 'Sometown',
            state: 'TX',
            zipCode: '75001',
            distance: 10,
            listPrice: '750,000',
            parcelNumber: '654321',
            bedrooms: 4,
            bathrooms: 3,
            acreage: 1.5,
            livingSqFt: 2800,
            totalSqFt: 3200,
            yearBuilt: 2015,
            zoning: 'Residential',
            sellerFee: 2.2,
            buyerFee: 2.7,
            creatorID: 348957341
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '789 Oak Boulevard',
            city: 'Yourtown',
            state: 'FL',
            zipCode: '33101',
            distance: 5,
            listPrice: '680,000',
            parcelNumber: '987654',
            bedrooms: 5,
            bathrooms: 4,
            acreage: 2.0,
            livingSqFt: 3400,
            totalSqFt: 3900,
            yearBuilt: 2012,
            zoning: 'Residential',
            sellerFee: 2.5,
            buyerFee: 3.0,
            creatorID: 34895734
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '123 Pine Street',
            city: 'Bigcity',
            state: 'NY',
            zipCode: '10001',
            distance: 15,
            listPrice: '850,000',
            parcelNumber: '556677',
            bedrooms: 6,
            bathrooms: 5,
            acreage: 2.5,
            livingSqFt: 4500,
            totalSqFt: 5000,
            yearBuilt: 2018,
            zoning: 'Mixed Use',
            sellerFee: 3.0,
            buyerFee: 3.5,
            creatorID: 348957341
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '890 Birch Lane',
            city: 'Oaktown',
            state: 'WA',
            zipCode: '98001',
            distance: 8,
            listPrice: '425,000',
            parcelNumber: '332211',
            bedrooms: 3,
            bathrooms: 2,
            acreage: 0.8,
            livingSqFt: 1600,
            totalSqFt: 1900,
            yearBuilt: 2008,
            zoning: 'Residential',
            sellerFee: 2.0,
            buyerFee: 2.3,
            creatorID: 34895734
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '246 Cedar Road',
            city: 'Greenfield',
            state: 'TX',
            zipCode: '75034',
            distance: 12,
            listPrice: '630,000',
            parcelNumber: '114477',
            bedrooms: 4,
            bathrooms: 3,
            acreage: 1.2,
            livingSqFt: 2900,
            totalSqFt: 3400,
            yearBuilt: 2010,
            zoning: 'Residential',
            sellerFee: 2.3,
            buyerFee: 2.8,
            creatorID: 34895734
        },
        {
          imageUrl: 'imgA.jpg',
          streetAddress: '159 Elmwood Drive',
          city: 'Springfield',
          state: 'IL',
          zipCode: '62704',
          distance: 7,
          listPrice: '540,000',
          parcelNumber: '123987',
          bedrooms: 3,
          bathrooms: 2,
          acreage: 0.5,
          livingSqFt: 1800,
          totalSqFt: 2200,
          yearBuilt: 2015,
          zoning: 'Residential',
          sellerFee: 2.4,
          buyerFee: 2.9,
          creatorID: 98562347
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '304 Lakeshore Avenue',
            city: 'Riverview',
            state: 'FL',
            zipCode: '33619',
            distance: 4,
            listPrice: '710,000',
            parcelNumber: '756412',
            bedrooms: 4,
            bathrooms: 3,
            acreage: 1.8,
            livingSqFt: 2600,
            totalSqFt: 3000,
            yearBuilt: 2011,
            zoning: 'Residential',
            sellerFee: 2.6,
            buyerFee: 3.1,
            creatorID: 34895734
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '88 Redwood Circle',
            city: 'Boulder',
            state: 'CO',
            zipCode: '80301',
            distance: 10,
            listPrice: '920,000',
            parcelNumber: '468975',
            bedrooms: 5,
            bathrooms: 4,
            acreage: 2.3,
            livingSqFt: 3200,
            totalSqFt: 3700,
            yearBuilt: 2017,
            zoning: 'Residential',
            sellerFee: 3.0,
            buyerFee: 3.4,
            creatorID: 98562349
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '650 Willowbrook Drive',
            city: 'Nashville',
            state: 'TN',
            zipCode: '37211',
            distance: 9,
            listPrice: '675,000',
            parcelNumber: '987123',
            bedrooms: 4,
            bathrooms: 3,
            acreage: 1.6,
            livingSqFt: 2800,
            totalSqFt: 3300,
            yearBuilt: 2014,
            zoning: 'Mixed Use',
            sellerFee: 2.5,
            buyerFee: 3.0,
            creatorID: 98562350
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '220 Pinecrest Court',
            city: 'San Diego',
            state: 'CA',
            zipCode: '92101',
            distance: 2,
            listPrice: '1,200,000',
            parcelNumber: '567843',
            bedrooms: 5,
            bathrooms: 4,
            acreage: 3.1,
            livingSqFt: 4000,
            totalSqFt: 4500,
            yearBuilt: 2020,
            zoning: 'Luxury Residential',
            sellerFee: 3.2,
            buyerFee: 3.6,
            creatorID: 98562351
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '478 Oak Valley Lane',
            city: 'Charlotte',
            state: 'NC',
            zipCode: '28205',
            distance: 6,
            listPrice: '590,000',
            parcelNumber: '345678',
            bedrooms: 3,
            bathrooms: 2,
            acreage: 1.0,
            livingSqFt: 2200,
            totalSqFt: 2600,
            yearBuilt: 2012,
            zoning: 'Residential',
            sellerFee: 2.4,
            buyerFee: 2.8,
            creatorID: 98562352
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '1023 Sycamore Avenue',
            city: 'Houston',
            state: 'TX',
            zipCode: '77001',
            distance: 7,
            listPrice: '680,000',
            parcelNumber: '789654',
            bedrooms: 4,
            bathrooms: 3,
            acreage: 1.2,
            livingSqFt: 2700,
            totalSqFt: 3200,
            yearBuilt: 2016,
            zoning: 'Residential',
            sellerFee: 2.7,
            buyerFee: 3.0,
            creatorID: 98562353
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '3349 Lakewood Drive',
            city: 'Seattle',
            state: 'WA',
            zipCode: '98101',
            distance: 3,
            listPrice: '830,000',
            parcelNumber: '112334',
            bedrooms: 5,
            bathrooms: 4,
            acreage: 2.5,
            livingSqFt: 3500,
            totalSqFt: 4000,
            yearBuilt: 2019,
            zoning: 'Residential',
            sellerFee: 3.1,
            buyerFee: 3.5,
            creatorID: 34895734
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '587 Pineview Court',
            city: 'Austin',
            state: 'TX',
            zipCode: '73301',
            distance: 8,
            listPrice: '750,000',
            parcelNumber: '669988',
            bedrooms: 4,
            bathrooms: 3,
            acreage: 1.4,
            livingSqFt: 2900,
            totalSqFt: 3300,
            yearBuilt: 2013,
            zoning: 'Residential',
            sellerFee: 2.9,
            buyerFee: 3.2,
            creatorID: 98562355
        },
        

        {
            imageUrl: 'imgA.jpg',
            streetAddress: '123 Oakridge Drive',
            city: 'Phoenix',
            state: 'AZ',
            zipCode: '85001',
            distance: 5,
            listPrice: '450,000',
            parcelNumber: '123450',
            bedrooms: 3,
            bathrooms: 2,
            acreage: 1.0,
            livingSqFt: 1800,
            totalSqFt: 2200,
            yearBuilt: 2015,
            zoning: 'Residential',
            sellerFee: 2.5,
            buyerFee: 3.0,
            creatorID: 78234523
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '246 Maplewood Lane',
            city: 'Denver',
            state: 'CO',
            zipCode: '80201',
            distance: 8,
            listPrice: '725,000',
            parcelNumber: '223344',
            bedrooms: 4,
            bathrooms: 3,
            acreage: 1.5,
            livingSqFt: 2600,
            totalSqFt: 3000,
            yearBuilt: 2018,
            zoning: 'Residential',
            sellerFee: 2.7,
            buyerFee: 3.2,
            creatorID: 78234524
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '789 Birchwood Drive',
            city: 'Seattle',
            state: 'WA',
            zipCode: '98101',
            distance: 6,
            listPrice: '830,000',
            parcelNumber: '445566',
            bedrooms: 5,
            bathrooms: 4,
            acreage: 2.2,
            livingSqFt: 3400,
            totalSqFt: 3900,
            yearBuilt: 2020,
            zoning: 'Luxury Residential',
            sellerFee: 3.1,
            buyerFee: 3.5,
            creatorID: 78234525
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '567 Redwood Avenue',
            city: 'San Francisco',
            state: 'CA',
            zipCode: '94101',
            distance: 3,
            listPrice: '1,450,000',
            parcelNumber: '778899',
            bedrooms: 6,
            bathrooms: 5,
            acreage: 3.0,
            livingSqFt: 4200,
            totalSqFt: 4700,
            yearBuilt: 2021,
            zoning: 'Commercial',
            sellerFee: 3.5,
            buyerFee: 4.0,
            creatorID: 78234526
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '902 Sycamore Lane',
            city: 'Dallas',
            state: 'TX',
            zipCode: '75201',
            distance: 7,
            listPrice: '540,000',
            parcelNumber: '556677',
            bedrooms: 4,
            bathrooms: 3,
            acreage: 1.3,
            livingSqFt: 2800,
            totalSqFt: 3300,
            yearBuilt: 2016,
            zoning: 'Residential',
            sellerFee: 2.8,
            buyerFee: 3.2,
            creatorID: 78234527
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '432 Pinecrest Road',
            city: 'Orlando',
            state: 'FL',
            zipCode: '32801',
            distance: 5,
            listPrice: '650,000',
            parcelNumber: '998877',
            bedrooms: 4,
            bathrooms: 3,
            acreage: 1.8,
            livingSqFt: 3000,
            totalSqFt: 3500,
            yearBuilt: 2017,
            zoning: 'Residential',
            sellerFee: 2.9,
            buyerFee: 3.3,
            creatorID: 78234528
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '789 Lakeshore Drive',
            city: 'Chicago',
            state: 'IL',
            zipCode: '60601',
            distance: 4,
            listPrice: '1,200,000',
            parcelNumber: '112233',
            bedrooms: 5,
            bathrooms: 4,
            acreage: 2.5,
            livingSqFt: 3900,
            totalSqFt: 4300,
            yearBuilt: 2019,
            zoning: 'Luxury Residential',
            sellerFee: 3.2,
            buyerFee: 3.6,
            creatorID: 78234529
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '301 Cypress Street',
            city: 'Miami',
            state: 'FL',
            zipCode: '33101',
            distance: 3,
            listPrice: '1,800,000',
            parcelNumber: '887766',
            bedrooms: 6,
            bathrooms: 5,
            acreage: 3.2,
            livingSqFt: 4500,
            totalSqFt: 5000,
            yearBuilt: 2022,
            zoning: 'Commercial',
            sellerFee: 3.6,
            buyerFee: 4.0,
            creatorID: 78234530
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '990 Walnut Avenue',
            city: 'Los Angeles',
            state: 'CA',
            zipCode: '90001',
            distance: 6,
            listPrice: '950,000',
            parcelNumber: '665544',
            bedrooms: 5,
            bathrooms: 4,
            acreage: 2.0,
            livingSqFt: 3500,
            totalSqFt: 4000,
            yearBuilt: 2021,
            zoning: 'Residential',
            sellerFee: 3.1,
            buyerFee: 3.5,
            creatorID: 78234531
        },
        {
            imageUrl: 'imgA.jpg',
            streetAddress: '603 Aspen Drive',
            city: 'Boston',
            state: 'MA',
            zipCode: '02101',
            distance: 5,
            listPrice: '880,000',
            parcelNumber: '332211',
            bedrooms: 4,
            bathrooms: 3,
            acreage: 1.6,
            livingSqFt: 2900,
            totalSqFt: 3400,
            yearBuilt: 2018,
            zoning: 'Residential',
            sellerFee: 2.7,
            buyerFee: 3.2,
            creatorID: 34895734
        },
    
      
      {
          imageUrl: 'imgA.jpg',
          streetAddress: '144 Magnolia Street',
          city: 'Tampa',
          state: 'FL',
          zipCode: '33602',
          distance: 5,
          listPrice: '680,000',
          parcelNumber: '778899',
          bedrooms: 4,
          bathrooms: 3,
          acreage: 1.1,
          livingSqFt: 2700,
          totalSqFt: 3100,
          yearBuilt: 2015,
          zoning: 'Residential',
          sellerFee: 2.5,
          buyerFee: 2.9,
          creatorID: 98562356
      }
      
    ]);

    return (
        <PropertyContext.Provider value={{ properties, setProperties }}>
            {children}
        </PropertyContext.Provider>
    );
};
